ALTER TABLE `test_papers`
  MODIFY `status` ENUM('DRAFT', 'SAVED', 'QUESTIONS_GENERATED', 'POSTED', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT';

UPDATE `test_papers`
SET `status` = 'POSTED'
WHERE `status` = 'PUBLISHED';

ALTER TABLE `test_papers`
  MODIFY `status` ENUM('DRAFT', 'SAVED', 'QUESTIONS_GENERATED', 'POSTED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT';
