"""Constants shared across all bulletproof modules."""

MODEL_FLASH = "gemini-2.5-flash"
MODEL_PRO   = "gemini-2.5-pro"

SCRIPT_UNICODE_RANGES = {
    "devanagari":    (0x0900, 0x097F),
    "bengali":       (0x0980, 0x09FF),
    "gurmukhi":      (0x0A00, 0x0A7F),
    "gujarati":      (0x0A80, 0x0AFF),
    "odia":          (0x0B00, 0x0B7F),
    "tamil":         (0x0B80, 0x0BFF),
    "telugu":        (0x0C00, 0x0C7F),
    "kannada":       (0x0C80, 0x0CFF),
    "malayalam":     (0x0D00, 0x0D7F),
    "arabic":        (0x0600, 0x06FF),
    "arabic_pfa":    (0xFB50, 0xFDFF),
    "arabic_pfb":    (0xFE70, 0xFEFF),
    "tibetan":       (0x0F00, 0x0FFF),
}

LEGACY_FONT_MAP = {
    "krutidevi":      ("devanagari", "kruti"),
    "krutidev":       ("devanagari", "kruti"),
    "kruti dev":      ("devanagari", "kruti"),
    "dvb":            ("devanagari", "kruti"),
    "shivaji":        ("devanagari", "kruti"),
    "shusha":         ("devanagari", "kruti"),
    "chanakya":       ("devanagari", "kruti"),
    "aakar":          ("devanagari", "kruti"),
    "priya":          ("devanagari", "kruti"),
    "akruti":         ("devanagari", "iscii"),
    "iscii":          ("devanagari", "iscii"),
    "saraswati":      ("devanagari", "kruti"),
    "yogesh":         ("devanagari", "kruti"),
    "lekhani":        ("devanagari", "kruti"),
    "sharda":         ("devanagari", "kruti"),
    "kiran":          ("devanagari", "kruti"),
    "mangal":         ("devanagari", "unicode"),
    "aparajita":      ("devanagari", "unicode"),
    "utsaah":         ("devanagari", "unicode"),
    "kokila":         ("devanagari", "unicode"),
    "sutonnymj":      ("bengali",    "bijoy"),
    "siyamrupali":    ("bengali",    "bijoy"),
    "bijoy":          ("bengali",    "bijoy"),
    "vrinda":         ("bengali",    "unicode"),
    "solaiman":       ("bengali",    "unicode"),
    "tsciilq":        ("tamil",      "tscii"),
    "bamini":         ("tamil",      "tscii"),
    "latha":          ("tamil",      "unicode"),
    "vani":           ("telugu",     "legacy"),
    "gautami":        ("telugu",     "legacy"),
    "hemalatha":      ("telugu",     "legacy"),
    "ramabhadra":     ("telugu",     "unicode"),
    "nudi":           ("kannada",    "nudi"),
    "akrutiknb":      ("kannada",    "nudi"),
    "tunga":          ("kannada",    "unicode"),
    "karthika":       ("malayalam",  "unicode"),
    "rachana":        ("malayalam",  "unicode"),
    "shreedev":       ("gujarati",   "legacy"),
    "shruti":         ("gujarati",   "unicode"),
    "akruti odia":    ("odia",       "akruti_odia"),
    "kalinga":        ("odia",       "unicode"),
    "asees":          ("gurmukhi",   "legacy"),
    "raavi":          ("gurmukhi",   "unicode"),
    "inpage":         ("arabic",     "inpage"),
    "jameel noori":   ("arabic",     "unicode"),
    "nastaliq":       ("arabic",     "unicode"),
    "nafees":         ("arabic",     "unicode"),
}

LANGUAGE_CONFIG = {
    "hindi":      {"folder_name": "hindi",     "script": "devanagari", "direction": "ltr"},
    "marathi":    {"folder_name": "marathi",   "script": "devanagari", "direction": "ltr"},
    "sanskrit":   {"folder_name": "sanskrit",  "script": "devanagari", "direction": "ltr"},
    "nepali":     {"folder_name": "nepali",    "script": "devanagari", "direction": "ltr"},
    "bengali":    {"folder_name": "bengali",   "script": "bengali",    "direction": "ltr"},
    "assamese":   {"folder_name": "assamese",  "script": "bengali",    "direction": "ltr"},
    "punjabi":    {"folder_name": "punjabi",   "script": "gurmukhi",   "direction": "ltr"},
    "gujarati":   {"folder_name": "gujarati",  "script": "gujarati",   "direction": "ltr"},
    "odia":       {"folder_name": "odia",      "script": "odia",       "direction": "ltr"},
    "odiya":      {"folder_name": "odia",      "script": "odia",       "direction": "ltr"},
    "tamil":      {"folder_name": "tamil",     "script": "tamil",      "direction": "ltr"},
    "telugu":     {"folder_name": "telugu",    "script": "telugu",     "direction": "ltr"},
    "kannada":    {"folder_name": "kannada",   "script": "kannada",    "direction": "ltr"},
    "malayalam":  {"folder_name": "malayalam", "script": "malayalam",  "direction": "ltr"},
    "urdu":       {"folder_name": "urdu",      "script": "arabic",     "direction": "rtl"},
    "arabic":     {"folder_name": "arabic",    "script": "arabic",     "direction": "rtl"},
    "persian":    {"folder_name": "persian",   "script": "arabic",     "direction": "rtl"},
    "sindhi":     {"folder_name": "sindhi",    "script": "arabic",     "direction": "rtl"},
    "english":    {"folder_name": "english",   "script": "latin",      "direction": "ltr"},
}
